### ISSUE TITLE
Merch: Navbar

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#10]
**Story**
As a user, I want to land on the Merch page 

**AC**
**When** the user navigates to the merch page
**Then** they should see the merch left nav

**DN**

- Add to my merch.html file to add bootstrap left nav bar
- NavBar in the comments

**Comment by EmileeA** [comment]
https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_nav_vertical&stacked=h
