### ISSUE TITLE
Merch: Merchandise Function

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#11]
# Story
As a user, I want to land on the Merch page and view all of the products. I want to be able to narrow down my selections by using the navigation on the left: Shirts/Posters/Vinyl

# AC
**When** the user navigates to the merch page
**Then** they should see the merch and merch left nav 
**And** have the ability to navigate to their selections. 

# DN

- Add to my merch.html file to add Div id's
- Style my page: -Page color light pink: #EAC1C1 / Text color dark purple: #491449
- Add merch array of objects to the js file.
- Pictures below in the comments. 
- printToDom function
- stringBuilder
- call my printToDom
- Add my event function
- add my getelementbyid id's
- init my event function
- init my js file

**Comment by EmileeA** [comment]
merch: 
t-shirts & vinyl:
https://pardonus.bandcamp.com/merch

https://f4.bcbits.com/img/0006187651_10.jpg

https://static1.squarespace.com/static/578ce65b15d5db22cae968bb/5ce6b610104c7b424bec349d/5ce870700d9297ced78798fb/1565223966245/?format=500w

https://cdn.shopify.com/s/files/1/0002/3461/8886/products/bKdUbXud_jpeg_1600x.jpg?v=1561719930


posters
-https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTexrzbeFC40nXcgJcg1vhjo1y3zh6nbNeKk6N12LRw-57e6WVVfg
https://imagery.zoogletools.com/u/281481/daec0bbcaee7d3d3210b97f85267e4a31ee5281e/original/pardon-us-bearon-logo.png
https://f4.bcbits.com/img/a0706942430_2.jpg

**Comment by EmileeA** [comment]
wireframe: 
![image](https://user-images.githubusercontent.com/36553398/65001832-bb53f580-d8b6-11e9-8be4-075f166795ea.png)
