### ISSUE TITLE
Music: Album Card Function

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#12]
# Story
As a user, I want to see a list of the bands albums in chronological order (newest first) with photos of the album covers

# Acceptance Criteria
**WHEN** The page loads
**THEN** The album covers with display vertically down the page
**AND** the name and year will be listed below each album

# Development Notes
* Font: Quicksand, backup Open Sans 
* Font color: #EAC1C1
* Image should use class `col-sm-8 offset-2`
* Image border 3px double #eac1c1 with 5px border-radius
* create array, `albumList`, of objects for each album: Title, Year, Img URL, Track List
* write function `printAlbums` to loop through array to print title/year/img to page. These should be wrapped in a card div but with no background color or border
* `printAlbums` should be part of an init function that runs on load
* use conditional statement in init function to prevent `printAlbums` from trying to run on other pages

**Comment by aclai4067** [comment]
![image](https://user-images.githubusercontent.com/47763728/64912056-821d5900-d6ef-11e9-85e9-a33000ea0855.png)

top image in this mockup reflects `printAlbums` bottom portion with the track list will be addressed in a separate issue
