### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#2]
# Story
As a user, I want to see the Navbar on the About, Music, and Gear page

# Acceptance Criteria
**WHEN** each link is clicked
**THEN** it should go to the corresponding pages

# Development Notes
* use a header tag to create navbar
* have pardon-us logo be clickable and go to home page
* use `<a href=""></a>` to navigate between pages

**Comment by djunaim** [comment]
![image](https://user-images.githubusercontent.com/53092019/64912361-9ebb9000-d6f3-11e9-9ba5-a43a6c7212d1.png)
