### ISSUE TITLE
Background Img for About & Music Page

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#4]
# Story
As a user, I want to see a cool band pic fill the page, with the band's signature girly vibe

# Acceptance Criteria
**WHEN** The page loads
**THEN** A static image will fill the page background
**AND** a translucent div will hold the content that scrolls over the background image

# Development Notes
* fade centered image to #EAC1C1 edges
* image will be centered and fill the page (no scroll, tile, etc)
* create a div that will go around the page content (after nav, before footer)
* content div background should be translucent #611A61
* give div a class `col-sm-8 offset-2`
* div should scroll over the background image, add a bunch of ipsum to test scroll and remove before committing

**Comment by aclai4067** [comment]
![image](https://user-images.githubusercontent.com/47763728/64912166-f7d5f480-d6f0-11e9-9e3c-ad968593d1c6.png)

**Comment by aclai4067** [comment]
background image: https://unsplash.com/photos/ErM56w1W2NY

include credit in alt: Photo by Christal Yuen

**Comment by aclai4067** [comment]
resource for fixed background image: https://css-tricks.com/perfect-full-page-background-image/
resource for gradients: https://css-tricks.com/radial-gradient-recipes/
