### ISSUE TITLE
Home Page: Image Divs

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#5]
# Story
As a user, I want to see and have the ability to interact with each of the images. .

# Acceptance Criteria
**WHEN** the page loads
**THEN** there will be 4 images for "About", "Merchandise", "Music", "Upcoming Tour Dates"
**WHEN** the image is clicked,
**THEN** it will go to the corresponding pages, except for "Upcoming Tour Dates"

# Development Notes
* use `light pink: #EAC1C1` as body background color
* use `dark purple: #491449` as border around different images
* use a `div` tag to hold all the `img` inside
* wrap `<img src="" alt="">` in the `<a href=""></a>` 
* link the different html pages in the href
* use below bootstrap code as reference to create grid with pictures

**Comment by djunaim** [comment]
![image](https://user-images.githubusercontent.com/53092019/64998943-a58d0300-d8ab-11e9-864f-f8f2547a0e54.png)

**Comment by djunaim** [comment]
![image](https://user-images.githubusercontent.com/53092019/64929148-cb50d400-d7e7-11e9-832d-d41776d7fc2d.png)

**Comment by djunaim** [comment]
About: 
![image](https://user-images.githubusercontent.com/53092019/64998714-dcaee480-d8aa-11e9-9ad7-4ad0761a8435.png)

**Comment by djunaim** [comment]
Merch: 
![image](https://user-images.githubusercontent.com/53092019/64998744-f18b7800-d8aa-11e9-9245-c78bbf252384.png)

**Comment by djunaim** [comment]
Music: 
![image](https://user-images.githubusercontent.com/53092019/64998772-08ca6580-d8ab-11e9-8b58-a3013f5d6131.png)

**Comment by djunaim** [comment]
Upcoming Tour Dates:
![image](https://user-images.githubusercontent.com/53092019/64998802-31525f80-d8ab-11e9-8cc2-049e06fc9b56.png)
