### ISSUE TITLE
Home Page: Upcoming Dates

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#6]
# Story
As a user, I want to know the different upcoming tour dates.

# Acceptance Criteria
**WHEN** the 'Upcoming Tour Dates' is clicked,
**THEN** it will show the upcoming shows

# Development Notes
* write `printToDOM` function
* use reference below for toggle function on the link so dates can be shown and hidden when clicked
* create a `<div id='upcomingTourDates'></div>` in html
* create an array of objects with dates, cities, time
* use for loop to print different dates to div with id=upcomingTourDates

**Comment by djunaim** [comment]
![image](https://user-images.githubusercontent.com/53092019/64999662-4250a000-d8ae-11e9-93c1-0b84aa34f7dd.png)
