### ISSUE TITLE
About Page: Artist Cards

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/foundations-group-project-pardon-us#9]
# Story
As a user, I want to see a description of all three artists, their photo, and a link to their social sites.

# Acceptance Criteria
WHEN the page loads
THEN there should be a paragraph about the band and a picture
AND when you scroll there should be a div of cards (three artists)
AND on the front of the card, it should be the artist picture 
AND on the back should be a quick description of them and their social sites
AND names will be in a div below

# Development Notes

- Font: Quicksand, backup Open Sans
- Font color: #000;
- Maybe use bootstrap: https://getbootstrap.com/docs/4.3/components/card/#using-grid-markup
- Use css transform property to create a 3D flip with the cards
- Maybe Read More link that will create a popup with more info about each band member
- Create and array of artists with objects(name, img, description, social sites) - printToDom

**Comment by CharityBunyon** [comment]
<img width="626" alt="Screen Shot 2019-09-16 at 6 52 52 PM" src="https://user-images.githubusercontent.com/52020883/65000959-40d5a680-d8b3-11e9-9b64-288584fc2fab.png">

<img width="658" alt="Screen Shot 2019-09-16 at 6 54 30 PM" src="https://user-images.githubusercontent.com/52020883/65001010-78dce980-d8b3-11e9-97cb-8a0bd00a32fa.png">

**Comment by CharityBunyon** [comment]
const printToDom = (divID, textToPrint) => {
    document.getElementById(divID).innerHTML = textToPrint;
}

**Comment by CharityBunyon** [comment]
Bootstrap Essentials:

- class="card-img-overlay" 
- https://getbootstrap.com/docs/4.3/utilities/colors/#background-color
- https://getbootstrap.com/docs/4.3/utilities/colors/#background-gradient
- https://getbootstrap.com/docs/4.3/components/card/#card-groups

**Comment by djunaim** [comment]
* in the Music section, the albums have shrunk. Another specific class might need to be created in your html
